config_dir: /home/ubuntu/Migrate-SFTP-Data/configs/
#config_dir: /Users/j9/Desktop/Migrate-SFTP-Data/configs/
files:
  con_0003_spending_and_revenue_all_years.csv:
    fourXFour: bpnb-jwfb
    dataset_name: CON-Spending and Revenue
    historic: con_0003_spending_and_revenue_all_years_historic.csv
    encoding: cp1252
  con_0005_vendor_payments_purchase_order_summary.csv:
    fourXFour: p5r5-fd7g
    historic: con_0005_vendor_payments_purchase_order_summary_historic.csv
    dataset_name: CON-Vendor Payments
    encoding: cp1252
  con_0006_vendor_payments_vouchers.csv:
    fourXFour:  n9pm-xkyq
    dataset_name: CON-Vouchers
    historic: con_0006_vendor_payments_vouchers_historic.csv
    encoding: cp1252
  con_0025_purchasing_commodity_data.csv:
    fourXFour: v3uy-zu9r
    historic: con_0025_purchasing_commodity_data_historic.csv
    dataset_name: CON-Purchasing Commodity data
    encoding: utf8
remote_dir: /CONT/
email_config_file: email_config_server.yaml
#email_config_file: email_config_gmail.yaml
download_dir: /home/ubuntu/Migrate-SFTP-Data/downloads/
#download_dir: /Users/j9/Desktop/Migrate-SFTP-Data/downloads/
string_number_fields: ['department_code', 'fiscal_year']


exception_logfile: exceptions.log
log_dir: logs/
app_name: Controller ETL Migration
socrata_client_config_fname: socrata_config.yaml
row_id_field: row_id
dataset_name_field: Socrata Dataset Name
fourXFour: fourXFour
dataset_records_cnt_field: DatasetRecordsCnt
isLoaded: isLoaded
src_records_cnt_field: SrcRecordsCnt
base_url: https://data.sfgov.org/resource/
sftp_config_file: sftp_configs.yaml
chunkSize: 10000
